/**
 * Copyright (c) 2010-2023 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.openhab.binding.icomforts30.internal.api.models.common;

/**
 * Response and request model for the Schedule Hold information
 *
 * @author Konstantin Panchenko- Initial contribution
 *
 */

// ToDo
public enum ErrorCodes {
    Unknown_Device_Detected_DEVICE2(10, "Unknown Device Detected"),
    Missing_DEVICE2(11, "Missing Device"),
    Incomplete_System(12, "Indoor Unit Not Detected"),
    Duplicate_Comfort_Sensor_ID(13, "Duplicate Comfort Sensor ID"),
    Too_Many_Devices_of_the_Same_Type(14, "Too Many Devices Of The Same Type"),
    Parameter_Missmatch_Detected_for_DEVICE2(15, "Parameter Mismatch Detected For Device"),
    Low_Ambient_HP_Heat_Lockout(18, "Low Ambient HP Heat Lockout"),
    High_Ambient_Auxiliary_Heat_Lockout(19, "High Ambient Auxiliary Heat Lockout"),
    Protocol_Upgrade_Required_DEVICE2(20, "Protocol Upgrade Required"),
    Incompatible_Equipment_Detected(21, "Incompatible Equipment Detected"),
    Over_Temperature_Protection(29, "Over Temperature Protection"),
    Low_Temperature_Protection(30, "Low Temperature Protection"),
    Lost_Communication_with_DEVICE2(31, "Lost Communication With Device"),
    Asynchronous_Reset_DEVICE2(32, "Device Resetting"),
    Must_Program_Unit_Capacity_for_DEVICE2(34, "Must Program Unit Capacity For Device"),
    Incorrect_Operation_of_DEVICE2(35, "Incorrect Operation Of Device"),
    Heating_when_Not_Requested_DEVICE2(36, "Heating When Not Requested"),
    Cooling_when_Not_Requested_DEVICE2(37, "Cooling When Not Requested"),
    Not_Heating_when_Requested_DEVICE2(38, "Not Heating When Requested"),
    Not_Cooling_when_Requested_DEVICE2(39, "Not Cooling When Requested"),
    HP_Heating_Lockout(40, "HP Heating Lockout"),
    DEVICE2_Control_Board_Replaced(41, "Device Control Board Replaced"),
    Communication_Problem(105, "Communication Error"),
    Low_AC_Line_Voltage(110, "GF Low AC Line Voltage"),
    Line_Polarity_Reversed(111, "GF Line Polarity Reversed"),
    No_Ground_Connection(112, "GF No Ground Connection"),
    High_AC_Line_Voltage(113, "GF High AC Line Voltage"),
    AC_Line_Frequency_Distortion_Prob(114, "AC Line Frequency/Distortion Error"),
    Low_Secondary_24VAC_Voltage(115, "Low Secondary (24VAC) Voltage"),
    High_Secondary_24VAC_Voltage(116, "IU High Secondary (24VAC) Voltage"),
    Poor_Ground(117, "IU Poor Ground"),
    Unresponsive_DEVICE2(120, "Unresponsive Device"),
    Active_Subnet_Controller_Missing(124, "Tstat Lost Communication To Smarthub"),
    Control_Hardware_Problem(125, "Control Hardware Error"),
    Control_Internal_Communication_Prob(126, "Control Internal Communication Error"),
    Configuration_Jumper_Missing(130, "Configuration Jumper Missing"),
    Corrupted_Control_Parameters(131, "Corrupted Control Parameters"),
    Failed_Flash_CRC_Check(132, "Device Control Software Fault"),
    reset(134, "Reset"),
    Outdoor_Temperature_Sensor_Problem(180, "Outdoor Temperature Sensor Error"),
    Suction_Pressure_Sensor_Problem(181, "OU Suction Pressure Transducer Fault"),
    Suction_Temperature_Sensor_Problem(182, "OU Suction Temperature Sensor Fault"),
    Liquid_Pressure_Sensor_Problem(183, "OU Liquid Pressure Sensor Error"),
    Liquid_Temperature_Sensor_Problem(184, "OU Liquid Temperature Sensor Error"),
    Rollout_Limit_Switch_Open(200, "GF Rollout Limit Switch Open"),
    Indoor_Blower_Motor_Problem(201, "IU Blower Motor Fault"),
    ID_Blower_Motor_Unit_Size_Mismatch(202, "IU Blower Motor & Unit Size Mismatch"),
    Invalid_Unit_Code(203, "IU Invalid Size Unit Code"),
    Gas_Valve_Problem(204, "GF Check Gas Valve"),
    Gas_Valve_Relay_Contact_Closed(205, "GF Gas Valve Relay Contact Closed"),
    Gas_Valve_2nd_Stage_Relay_Failure(206, "GF Gas Valve 2nd Stage Relay Fault"),
    HSI_Sensed_Open(207, "GF HSI Sensed Open"),
    Low_Pressure_Switch_Open(223, "GF Low Pressure Switch Open"),
    Low_Pressure_Switch_Stuck_Closed(224, "GF Low Pressure Switch Stuck Closed"),
    High_Press_Switch_Failed_to_Close(225, "GF High Pressure Switch Failed to Close"),
    High_Pressure_Switch_Stuck_Closed(226, "GF High Pressure Switch Stuck Closed"),
    Lo_Pressure_Switch_Open_in_Run_Mode(227, "GF Low Pressure Switch Open in Run Mode"),
    Inducer_Press_Switch_Calib_Failure(228, "GF Inducer Calibration Issue"),
    Ignition_on_High_Fire(229, "GF Ignition On High Fire"),
    Low_Flame_Current_Run_Mode(240, "GF Low Flame Current - Run Mode"),
    Flame_Out_of_Sequence_Still_Present(241, "GF Flame Out Of Sequence-Still Present"),
    Primary_Limit_Switch_Open(250, "GF Primary Limit Switch Open"),
    Discharge_Air_Temperature_High(252, "IU Discharge Air Temperature High"),
    Watchguard_Flame_Failure_on_Ignite(270, "GF Flame Failed To Ignite"),
    Watchguard_Low_Press_Switch_Open(271, "GF Low Press Switch Open"),
    Watchguard_LoPressSwitchOpenRunMode(272, "GF Low Press Switch Open Run Mode"),
    Watchguard_Flame_Fail_in_Run_Mode(273, "GF Flame Fail In Run Mode"),
    Watchguard_Primary_LimitSwitch_Open(274, "GF Primary Limit Switch Open"),
    Watchguard_Flame_OutofSeq_NoFlame(275, "GF Flame Out Of Seq. No Flame"),
    Watchguard_Calibration_Failure(276, "GF Calibration Failure"),
    Ignition_Circuit_Problem(290, "GF Ignition Circuit Fault"),
    Heat_Airflow_Restricted_Below_Min(291, "GF Heat Airflow Below Min"),
    Indoor_Blower_Motor_Start_Problem(292, "ID Blower Motor Start Fault"),
    Inducer_Motor_Overcurrent(294, "GF Inducer Motor Overcurrent"),
    Indoor_Blower_Over_Temperature(295, "ID Blower Over Temperature"),
    Discharge_Air_Temp_Sensor_Problem(310, "Discharge Air Temp Sensor Error"),
    Heat_Rate_Reduced_to_Match_Airflow(311, "GF Heat Rate Reduced To Match Airflow"),
    ReducedAirflow_IndoorBlower_Cutback(312, "Reduced Airflow-Indoor Blower Cutback"),
    Indoor_OutdoorUnit_CapacityMismatch(313, "Indoor/Outdoor Unit Capacity Mismatch"),
    Link_Relay_Problem(330, "Link Relay Problem"),
    RSBus_Communication_Link_Problem(331, "RSBus Communication Link Problem"),
    Relay_Y1_Stuck(344, "GF IFC Relay Y1 Stuck"),
    Relay_O_Failure(345, "Relay O Failure"),
    HP_Jumper_not_Removed(346, "AH HP Jumper Not Removed"),
    Relay_Y1_Failure(347, "IU or EIM Relay Y1 Fault"),
    Relay_Y2_Failure(348, "IU Relay Y2 Fault"),
    IFC_Error_Check_Jumper_O_to_R(349, "GF IFC Error Check Jumper O To R"),
    Electric_Heat_not_Configured(350, "AH Electric Heat Not Configured"),
    Electric_Heat_Stage_1_Problem(351, "AH Electric Heat Stage 1 Fault"),
    Electric_Heat_Stage_2_Problem(352, "AH Electric Heat Stage 2 Fault"),
    Electric_Heat_Stage_3_Problem(353, "AH Electric Heat Stage 3 Fault"),
    Electric_Heat_Stage_4_Problem(354, "AH Electric Heat Stage 4 Fault"),
    Electric_Heat_Stage_5_Problem(355, "AH Electric Heat Stage 5 Fault"),
    Sequencer_Failed_to_Close(356, "Sequencer Failed to Close"),
    Sequencer_Stuck_Closed(357, "Sequencer Stuck Closed"),
    Control_Error_Check_Jumper_O_to_R(358, "AH Control Error - Check Jumper O To R"),
    Interlock_Switch_Open(370, "GF Interlock Switch Open"),
    Float_Switch_Sensed_Open(371, "AH Float Switch Sensed Open"),
    Interlock_Relay_Failure(380, "EIM Interlock Relay Fault"),
    Interlock_Relay_Stuck(381, "EIM Interlock Relay Stuck"),
    Relay_W1_Failure(382, "EIM Relay W1 Fault"),
    LSOM_Comp_Internal_Overload_Tripped(400, "OU LSOM Compressor Internal Overload Tripped"),
    Compressor_Long_Run_Cycle(401, "OU Compressor Long Run Cycle"),
    Outdoor_Unit_System_Pressure_Trip(402, "OU System Pressure Trip"),
    Compressor_Short_Cycling(403, "OU Compressor Short-Cycling"),
    Compressor_Rotor_Locked(404, "OU Compressor Rotor Locked"),
    Compressor_Open_Circuit(405, "OU Compressor Open Circuit"),
    Compressor_Open_Start_Circuit(406, "OU Compressor Open Start Circuit"),
    Compressor_Open_Run_Circuit(407, "OU Compressor Open Run Circuit"),
    Compressor_Contactor_Welded(408, "OU Compressor Contactor Welded"),
    Compressor_Voltage_Low(409, "OU Control Board Low 24VAC"),
    Open_Low_Pressure_Switch(410, "OU Open Low Pressure Switch"),
    Low_Pressure_Switch_Strikes_Lockout(411, "OU Low Pressure Switch Strikes Lockout"),
    Open_High_Pressure_Switch(412, "OU Open High Pressure Switch"),
    Hi_Pressure_Switch_Strikes_Lockout(413, "OU High Pressure Switch Strikes Lockout"),
    High_Discharge_Line_Temperature(414, "OU High Discharge Line Temperature"),
    Hi_Disch_Line_Temp_Strikes_Lockout(415, "OU High Discharge Line Temp Strikes Lockout"),
    Outdoor_Coil_Sensor_Faulty(416, "OU Coil Sensor Faulty"),
    Discharge_Sensor_Faulty(417, "OU Discharge Sensor Faulty"),
    W_Output_Hardware_Fault(418, "OU EIM W Output Hardware Fault"),
    W_Output_Hardware_Fault_Lockout(419, "OU EIM W Output Hardware Fault Lockout"),
    Defrost_Out_of_Control(420, "AH EIM Defrost Out Of Cycle"),
    W_External_Miswire_Fault(421, "OU EIM W External Miswiring Fault"),
    Compressor_Top_Cap_Switch_Open(422, "OU Compressor Top Cap Switch Open"),
    OD_Inverter_CT_Circuit_Problem(423, "OU Inverter CT Circuit Fault"),
    OD_Liquid_Line_Sensor_Faulty(424, "OU Liquid Line Sensor Faulty"),
    Compressor_speed_limited_by_OD_temperature(425, "OU Compressor Speed Limited By OD Temperature"),
    Excessive_Inverter_Alarms(426, "OU Excessive Inverter Alarms"),
    OD_Inverter_DC_Peak_Fault(427, "OU Inverter DC Peak Fault"),
    OD_Inverter_High_Main_Input_Current(428, "OU Inverter High Main Input Current"),
    OD_Inverter_DC_Link_Low_Voltage(429, "OU Inverter DC Link Low Voltage"),
    OD_Inverter_Compressr_Startup_fail(430, "OU Inverter Compressor Startup fail"),
    OD_Inverter_PFC_Fault(431, "OU Inverter PFC Fault"),
    OD_Inverter_DC_Link_High_Voltage(432, "OU Inverter DC Link High Voltage"),
    OD_Inverter_Compressor_Overcurrent(433, "OU Inverter Compressor Overcurrent"),
    OD_Inverter_Comm_Error_to_Main_Control(434, "OU Inverter Communication Error To Main Control"),
    OD_Inverter_EEPROM_Checksum_Fault(435, "OU Inverter EEPROM Checksum Fault"),
    OD_Inverter_High_Heat_Sink_Temperature(436, "OU Inverter High Heat-Sink Temperature"),
    OD_Inverter_Heat_Sink_Temp_Sensor_Fault(437, "OU Inverter Heat-Sink Temp Sensor Fault"),
    OD_Inverter_PFC_Input_Overcurrent(438, "OU Inverter PFC Input Overcurrent"),
    OD_Inverter_Compressor_Slowdown_High_Input_Current(439, "OU Inverter Compressor Slowdown - High Input Current"),
    OD_Inverter_Compressor_Slowdown_High_Heat_Sink_Temperature(440,
            "OU Inverter Compressor Slowdown - High Heat-Sink Temperature"),
    OD_Inverter_Compressor_Slowdown_High_Compressor_Current(441,
            "OU Inverter Compressor Slowdown - High Compressor Current"),
    Compressor_Top_Cap_Switch_Strikes_Lockout(442, "OU Compressor Top Cap Switch Strikes Lockout"),
    MUC_Unit_Code_to_Inverter_Model_Mismatch(443, "OU MUC Unit Code To Inverter Model Mismatch"),
    Reversing_Valve_Relay_Failed_to_Close(444, "HP Reversing Valve Relay Or Solenoid Fault"),
    OD_Low_Suction_Pressure_Fault(446, "OU Low Suction Pressure Fault"),
    OD_High_Liquid_Line_Temperature(447, "OU High Liquid Line Temperature"),
    OD_High_Liquid_Line_Temperature_Strikes_Lockout(448, "OU High Liquid Line Temp Strikes Lockout"),
    PureAir_Pressure_Sensor_Fault(500, "PA Differential Pressure Sensor Fault"),
    PureAir_UV_Sensor_Fault(501, "PA UV Sensor Fault"),
    PureAir_UV_Lamp_Off(502, "PA UV Lamp Off"),
    PureAir_Filter_Life_10(503, "PA Filter Life At 10%"),
    PureAir_Filter_Life_0(504, "PA Filter Life At 0%"),
    PureAir_Model_Selection_Changed(505, "PA Model Selection Changed"),
    PureAir_UV_Lamp_Life_0(506, "PA Lamp At 0% life"),
    Filter_Calibration_Fail(507, "PA Filter Calibration Failure"),
    Low_Damper_24VAC_Voltage(530, "ZS Low Damper 24VAC Voltage"),
    Zoning_Pressure_Switch_Opened_high_pressure(532, "ZS Zoning Pressure Switch Opened (High Pressure)"),
    Zone_1_Temp_Sensor_Problem(542, "ZS Zone 1 Temp Sensor Fault"),
    Zone_2_Temp_Sensor_Problem(543, "ZS Zone 2 Temp Sensor Fault"),
    Zone_3_Temp_Sensor_Problem(544, "ZS Zone 3 Temp Sensor Fault"),
    Zone_4_Temp_Sensor_Problem(545, "ZS Zone 4 Temp Sensor Fault"),
    ZS_Parameters_Resetting_From_Restored_Power(546, "ZS Parameters resetting from restored power"),
    ZS_Parameters_Resetting_From_System_Interruption(547, "ZS Parameters resetting from system interruption"),
    ZS_Humidity_Sensor_Error(548, "ZS Humidity Sensor Error"),
    ZS_Zone_Sensor_Lost_Communication(551, "ZS Zone Sensor Lost Communication"),
    Load_Shed_Event(600, "Load Shed Event"),
    OD_Unit_Low_Ambient_Operational_Lockout(601, "OU Low Ambient Operational Lockout"),
    OD_Unit_High_Ambient_Operational_Lockout(602, "OD Unit High Ambient Operational Lockout"),
    Service_Alert(603, "Service Alert"),
    Cooling_Capacity_Degradation(604, "Cooling Capacity Degradation"),
    Low_Room_Temperature_Detected(610, "Low Room Temperature Detected"),
    High_Room_Temperature_Detected(611, "High Room Temperature Detected"),
    Comfort_Sensor_Temp_Sensor_Problem(700, "Thermostat  Temp Sensor Error"),
    TSTAT_Temp_Above_Limit(701, "Thermostat Temp Above Limit"),
    TSTAT_Temp_Below_Limit(702, "The thermostat is reading indoor temperatures below the pre-programmed limit"),
    Comfort_Sensor_Humid_Sensor_Problem(703, "Thermostat Humid Sensor Error"),
    TSAT_Indoor_Humidity_Above_Limit(704,
            "The thermostat is reading indoor humidity levels above the pre-programmed limit"),
    TSAT_Indoor_Humidity_Below_Limit(705,
            "The thermostat is reading indoor humidity levels below the pre-programmed limit"),
    Lost_Communication_with_Server(801, "Lost Communication with Server"),
    Lost_Wireless_Connection_with_WAP(802, "Lost Wireless Connection with WAP"),
    Temperature_Control_Problem(900, "Temperature Control Error"),
    Smart(901, "Inconsistent Indoor Temp"),
    Ohm_Check(999, "Ohm check - The ohm reading in the system is either too high or too low"),
    Missing_Base(65537, "Missing Base"),
    Missing_Base_1(65538, "Missing Mag Mount Base"),
    Missing_TSTAT(65539, "Thermostat Lost Connection Or Internal Fault"),
    Missing_HD_Wall_display(65540, "Missing HD wall display"),
    Download_Failed(65541, "Download Failed"),
    Update_Failed(65542, "Update Failed "),
    Firmware_Updated(65543, "Firmware Updated"),
    Too_Many_Siblings(65544, "More Than 8 Tstats In A Group"),
    Cooling_Prognostics_Alert(65545, "Cooling Capacity Alert");

    private final int code;
    private final String description;

    private ErrorCodes(int code, String description) {
        this.code = code;
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public int getCode() {
        return code;
    }

    @Override
    public String toString() {
        return code + ": " + description;
    }
}
